name: AdopBox
description: AdopBox App.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  #dependencies injection
  get_it: ^7.2.0

  #location
  location: ^4.4.0
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.1

  #for double tap error
  easy_debounce: ^2.0.3

  #for rewsponsive
  flutter_screenutil: ^5.7.0

  #lotti file
  lottie: ^2.2.0
  #svg
  flutter_svg:

  #Device path get
  path_provider: ^2.0.13

  #print Log
  logger: ^1.2.2

  #bloc
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0

  #Getx
  get: ^4.6.5

  #hive db
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #locatligation
#  easy_localization: ^3.0.1

  #permision
  permission_handler: ^10.2.0

  #htp
  http: ^0.13.5
  dio: ^5.1.1

  #image
  image_picker: ^0.8.7
  camera: ^0.9.4+5
  cached_network_image: ^3.2.3

  #show case
  showcaseview: ^1.1.6

  #need dependency
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  flutter_animation_progress_bar: ^2.3.1
  flutter_html: ^3.0.0-alpha.6

#  ssl commerce
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  fluttertoast: ^8.2.1

#  youtube player
  youtube_player_flutter: ^8.1.2

#  file picker
  file_picker: ^5.2.7

#  rating bar
  flutter_rating_bar: ^4.0.1
#  otp
  pin_code_fields: ^7.4.0
#  connectivity
  connectivity_plus: ^3.0.6
#  number picker
  numberpicker: ^2.1.2

  quiver: ^3.2.1

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5

dev_dependencies:
  change_app_package_name: ^1.1.0
  build_runner: ^2.3.3
  json_serializable:
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"



  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/fonts/


  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
        - asset: assets/fonts/MavenPro-Bold.ttf
        - asset: assets/fonts/MavenPro-ExtraBold.ttf
        - asset: assets/fonts/MavenPro-Medium.ttf
        - asset: assets/fonts/MavenPro-SemiBold.ttf
        - asset: assets/fonts/MavenPro-Black.ttf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf

