///firebase api
const String BASE_URL_FIREBASE = 'https://fcm.googleapis.com/fcm/send';
const String KEY_SERVER = 'AAAAU1d6Qbg:APA91bF9w1-80B0ef4YoOxMUOZfP-b8IR1NMoZwSUPwVWP2ArhnSrIHlMGj-C20ZSep2TzgRUUzE8dJphsrCNhtUDKnNYUl213El1sO_Y0jeKVwHy9NbO-cyhgqqshYv5AbBdLSTjOlI';
const String SENDER_ID = '357949915576';


//base url of api
//staging
const BASE_URL = "https://staging.somriddhi.com/api/";
const BASE_URL_IMAGE = "https://staging-lms.sgp1.digitaloceanspaces.com/";


//route name
const MAIN_PAGE = "/main_page";
const HOME_PAGE = "/home_page";
const LOGIN_PAGE= "/LOGIN_PAGE";
const LOGIN_PAGE_INTRO = "/LOGIN_PAGE_INTRO";
const SIGNUP_SUCESS_PAGE = "/SIGNUP_SUCESS_PAGE";
const SIGNUP_PAGE= "/SIGNUP_PAGE";
const OTP_PAGE= "/OTP_PAGE";
const INFO_PAGE= "/INFO_PAGE";

//paswword
const FORGET_PASSWORD_PAGE = "/forget_pass_page";
const FORGET_PASS_MAIL_SUCESS_PAGE = "/FORGET_PASS_MAIL_SUCESS_PAGE";
const PASSWORD_SET_PAGE = "/PASSWORD_SET_PAGE";
const FORGET_PASSWORD_MAIL_PAGE = "/FORGET_PASSWORD_MAIL_PAGE";
const FORGET_OTP_PAGE= "/FORGET_OTP_PAGE";
//Settings page
const SETTINGS_PAGE = "/SETTINGS_PAGE";

//Profile page
const PROFILE_PAGE = "/PROFILE_PAGE";

//course
const LEARNING_HISORY = "/LEARNING_HISORY";
const LEARNING_HISORY_DEATILS = "/LEARNING_HISORY_DEATILS";
const COURSE_DETAILS_PAGE = "/COURSE_DETAILS_PAGE";
const CATGEGORY_COURSE_PAGE = "/CATGEGORY_COURSE_PAGE";
const PURCHED_COURSE_PROGRESS_PAGE = "/PURCHED_COURSE_PROGRESS_PAGE";

//Quize page
const QUIZ_PAGE = "/QUIZ_PAGE";
const QUIZ_RESULT_PAGE = "/QUIZ_RESULT_PAGE";

//Teacher Details Page
const TEACHER_DETAILS_PAGE="/TEACHER_DETAILS_PAGE";

//Cart Page
const CART_PAGE="/CART_PAGE";

//Class room Page
const CLASS_ROOM_PAGE="/CLASS_ROOM_PAGE";

//About Page
const ABOUT_PAGE="/ABOUT_PAGE";
const POLICY_PAGE="/POLICY_PAGE";
const REFUND_POLICY_PAGE="/REFUND_POLICY_PAGE";
const TRAM_AND_CONDITION_PAGE="/TRAM_AND_CONDITION_PAGE";
const CERTIFICATE_PAGE="/CERTIFICATE_PAGE";
const FAQ_PAGE="/FAQ_PAGE";

//edit profile
const EDITE_PROFILE_PAGE="/EDITE_PROFILE_PAGE";
const PASSWORD_CHANGE_PAGE="/PASSWORD_CHANGE_PAGE";
const SLIDER_PAGE="/SLIDER_PAGE";

//Course query
const COURSE_QUERY_LIST ="/COURSE_QUERY_LIST";
const COURSE_QUERY_CREATE ="/COURSE_QUERY_CREATE";
const COURSE_QUERY_DEATILS ="/COURSE_QUERY_DEATILS";

//Assisment
const HOME_ASSESMENT ="/HOME_ASSESMENT";
const SITUATIONAL_ASSESMENT ="/SITUATIONAL_ASSESMENT";
const ASSESMENT_DETAILS ="/ASSESMENT_DETAILS";






